routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');

Route::group(['middleware' => 'CheckLogin'],function(){

	Route::group(['prefix' => 'lop','as' => 'lop.'],function(){
		Route::get('','LopController@view_all')->name('view_all');
		Route::get('view_insert','LopController@view_insert')->name('view_insert');
		Route::post('process_insert','LopController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
		Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
		Route::get('delete/{ma}','LopController@delete')->name('delete');
	});

	Route::group(['prefix' => 'sinh_vien','as' => 'sinh_vien.'],function(){
		Route::get('','SinhVienController@view_all')->name('view_all');
		Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
		Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
	});

	Route::group(['prefix' => 'mon','as' => 'mon.'],function(){
		Route::get('','MonController@view_all')->name('view_all');
		Route::get('view_update_mon_nganh','MonController@view_update_mon_nganh')->name('view_update_mon_nganh');
		Route::post('process_update_mon_nganh','MonController@process_update_mon_nganh')->name('process_update_mon_nganh');
	});
	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
	Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');
	Route::group(['prefix' => 'phan_cong','as' => 'phan_cong.'],function(){
		Route::get('','PhanCongController@view_phan_cong')->name('view_phan_cong');
		Route::post('','PhanCongController@process_phan_cong')->name('process_phan_cong');
	});
});


Route::get('','Controller@master');
Route::get('view_login','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVien', 'prefix' => 'giao_vien','as' => 'giao_vien.'],function(){
	Route::get('choose_diem_danh','DiemDanhController@choose_diem_danh')->name('choose_diem_danh');
	Route::post('view_diem_danh','DiemDanhController@view_diem_danh')->name('view_diem_danh');
	Route::post('process_diem_danh','DiemDanhController@process_diem_danh')->name('process_diem_danh');
});

app/Models/Lop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lop extends Model
{
    protected $table = 'lop';
    protected $fillable = [
    	'ten',
    	'ten_tieng_anh',
    ];	
    public $timestamps = false;
    protected $primaryKey = 'ma';

}

app/Http/Controllers/LopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Lop;


class LopController
{
	public function view_all()
	{
		$array_lop = Lop::get();
		return view('lop.view_all',compact('array_lop'));
	}
	public function view_insert()
	{
		return view('view_insert');
	}
	public function process_insert(Request $rq)
	{
		Lop::create($rq->all());

		return redirect()->route('view_all');
	}
	public function view_update($ma)
	{
		// $lop = Lop::where('ma','=',$ma)->first();

		$lop = Lop::find($ma);

		return view('view_update',compact('lop'));
	}
	public function process_update($ma, Request $rq)
	{
		Lop::find($ma)->update($rq->all());

		return redirect()->route('view_all');
	}
	public function delete($ma)
	{
		// Lop::find($ma)->delete();

		Lop::destroy($ma);

		return redirect()->route('view_all');
	}
}

resources/views/lop/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>
	đây là danh sách lớp
</h1>
<a href="{{ route('lop.view_insert') }}">
	Thêm
</a>
<table class="table">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Tên tiếng Anh</th>
		<th>Sửa</th>
	</tr>
	@foreach ($array_lop as $lop)
		<tr>
			<td>
				{{ $lop->ma }}
			</td>
			<td>
				{{ $lop->ten }}
			</td>
			<td>
				{{ $lop->ten_tieng_anh }}
			</td>
			<td>
				<a href="{{ route('lop.view_update',['ma' => $lop->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('lop.delete',['ma' => $lop->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

@endsection

resources/views/lop/view_insert.blade.php
<form action="{{ route('process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	Tên tiếng Anh
	<input type="text" name="ten_tieng_anh">
	<button>Thêm</button>
</form>

resources/views/lop/view_update.blade.php
<form action="{{ route('process_update',['ma' => $lop->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $lop->ten }}">
	<br>
	Tên tiếng Anh
	<input type="text" name="ten_tieng_anh" value="{{ $lop->ten_tieng_anh }}">
	<button>Sửa</button>
</form>