routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');

Route::group(['middleware' => 'CheckLogin'],function(){

	Route::group(['prefix' => 'lop','as' => 'lop.'],function(){
		Route::get('','LopController@view_all')->name('view_all');
		Route::get('view_insert','LopController@view_insert')->name('view_insert');
		Route::post('process_insert','LopController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
		Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
		Route::get('delete/{ma}','LopController@delete')->name('delete');
	});

	Route::group(['prefix' => 'sinh_vien','as' => 'sinh_vien.'],function(){
		Route::get('','SinhVienController@view_all')->name('view_all');
		Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
		Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
	});

	Route::group(['prefix' => 'mon','as' => 'mon.'],function(){
		Route::get('','MonController@view_all')->name('view_all');
		Route::get('view_update_mon_nganh','MonController@view_update_mon_nganh')->name('view_update_mon_nganh');
		Route::post('process_update_mon_nganh','MonController@process_update_mon_nganh')->name('process_update_mon_nganh');
	});
	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
	Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');
	Route::group(['prefix' => 'phan_cong','as' => 'phan_cong.'],function(){
		Route::get('','PhanCongController@view_phan_cong')->name('view_phan_cong');
		Route::post('','PhanCongController@process_phan_cong')->name('process_phan_cong');
	});
});


Route::get('','Controller@master');
Route::get('view_login','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVien', 'prefix' => 'giao_vien','as' => 'giao_vien.'],function(){
	Route::get('choose_diem_danh','DiemDanhController@choose_diem_danh')->name('choose_diem_danh');
	Route::post('view_diem_danh','DiemDanhController@view_diem_danh')->name('view_diem_danh');
	Route::post('process_diem_danh','DiemDanhController@process_diem_danh')->name('process_diem_danh');
});

app/Models/GiaoVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class GiaoVien extends Model
{
    protected $table = 'giao_vien';
    public $timestamps = false;
}

app/Http/Controllers/GiaoVienController.php
<?php

namespace App\Http\Controllers;

use App\Models\GiaoVien;
use Illuminate\Http\Request;

class GiaoVienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\GiaoVien  $giaoVien
     * @return \Illuminate\Http\Response
     */
    public function show(GiaoVien $giaoVien)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\GiaoVien  $giaoVien
     * @return \Illuminate\Http\Response
     */
    public function edit(GiaoVien $giaoVien)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\GiaoVien  $giaoVien
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, GiaoVien $giaoVien)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\GiaoVien  $giaoVien
     * @return \Illuminate\Http\Response
     */
    public function destroy(GiaoVien $giaoVien)
    {
        //
    }
}

resources/views/giao_vien/choose_diem_danh.blade.php
@if (Session::has('error'))
	<h1>
		{{ Session::get('error') }}
	</h1>
@endif
<form action="{{ route('giao_vien.view_diem_danh') }}" method="post">
	{{ csrf_field() }}
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn môn
	<select name="ma_mon">
		@foreach ($array_mon as $mon)
			<option value="{{ $mon->ma }}">
				{{ $mon->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Chọn</button>
</form>

resources/views/giao_vien/view_diem_danh.blade.php
@if (Session::has('error'))
	<h1>
		{{ Session::get('error') }}
	</h1>
@endif
<form action="{{ route('giao_vien.view_diem_danh') }}" method="post">
	{{ csrf_field() }}
	Chọn lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}" 
			@if ($lop->ma == $ma_lop)
				selected 
			@endif>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	Chọn môn
	<select name="ma_mon">
		@foreach ($array_mon as $mon)
			<option value="{{ $mon->ma }}" 
			@if ($mon->ma == $ma_mon)
				selected 
			@endif>
				{{ $mon->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Chọn</button>
</form>
<form action="{{ route('giao_vien.process_diem_danh') }}" method="post">
	{{ csrf_field() }}
	<input type="hidden" name="ma_lop" value="{{ $ma_lop }}">
	<input type="hidden" name="ma_mon" value="{{ $ma_mon }}">
<table>
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Tình trạng đi học</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ma }}
			</td>
			<td>
				{{ $sinh_vien->ten }}
			</td>
			<td>
				<input type="radio" name="tinh_trang_di_hoc[{{ $sinh_vien->ma }}]" value="1" checked>Đi học
				<input type="radio" name="tinh_trang_di_hoc[{{ $sinh_vien->ma }}]" value="2"
				@if (isset($array[$sinh_vien->ma]) && $array[$sinh_vien->ma]==2)
					checked 
				@endif>Nghỉ
			</td>
		</tr>
	@endforeach
</table>
<button>Điểm danh</button>
<script type="text/javascript">
	
	
</script>
</form>