routes/web.php
<?php

Route::get('view_sinh_vien_import','SinhVienController@view_sinh_vien_import');
Route::post('process_sinh_vien_import','SinhVienController@process_sinh_vien_import')->name('process_sinh_vien_import');

Route::group(['middleware' => 'CheckLogin'],function(){

	Route::group(['prefix' => 'lop','as' => 'lop.'],function(){
		Route::get('','LopController@view_all')->name('view_all');
		Route::get('view_insert','LopController@view_insert')->name('view_insert');
		Route::post('process_insert','LopController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','LopController@view_update')->name('view_update');
		Route::post('process_update/{ma}','LopController@process_update')->name('process_update');
		Route::get('delete/{ma}','LopController@delete')->name('delete');
	});

	Route::group(['prefix' => 'sinh_vien','as' => 'sinh_vien.'],function(){
		Route::get('','SinhVienController@view_all')->name('view_all');
		Route::get('view_insert','SinhVienController@view_insert')->name('view_insert');
		Route::post('process_insert','SinhVienController@process_insert')->name('process_insert');
		Route::get('view_update/{ma}','SinhVienController@view_update')->name('view_update');
		Route::post('process_update/{ma}','SinhVienController@process_update')->name('process_update');
		Route::get('delete/{ma}','SinhVienController@delete')->name('delete');
	});

	Route::group(['prefix' => 'mon','as' => 'mon.'],function(){
		Route::get('','MonController@view_all')->name('view_all');
		Route::get('view_update_mon_nganh','MonController@view_update_mon_nganh')->name('view_update_mon_nganh');
		Route::post('process_update_mon_nganh','MonController@process_update_mon_nganh')->name('process_update_mon_nganh');
	});
	Route::get('view_upload_avatar','Controller@view_upload_avatar')->name('view_upload_avatar');
	Route::post('process_upload_avatar','Controller@process_upload_avatar')->name('process_upload_avatar');
	Route::group(['prefix' => 'phan_cong','as' => 'phan_cong.'],function(){
		Route::get('','PhanCongController@view_phan_cong')->name('view_phan_cong');
		Route::post('','PhanCongController@process_phan_cong')->name('process_phan_cong');
	});
});


Route::get('','Controller@master');
Route::get('view_login','Controller@view_login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::group(['middleware' => 'CheckGiaoVien', 'prefix' => 'giao_vien','as' => 'giao_vien.'],function(){
	Route::get('choose_diem_danh','DiemDanhController@choose_diem_danh')->name('choose_diem_danh');
	Route::post('view_diem_danh','DiemDanhController@view_diem_danh')->name('view_diem_danh');
	Route::post('process_diem_danh','DiemDanhController@process_diem_danh')->name('process_diem_danh');
});

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    protected $fillable = [
    	'ten',
    	'email',
    	'ngay_sinh',
    	'gioi_tinh',
    	'ma_lop',
    ];	
    public $timestamps = false;
    protected $primaryKey = 'ma';
    public function lop()
    {
        return $this->belongsTo('App\Models\Lop', 'ma_lop');
    }
    public function getTenGioiTinhAttribute()
    {
        if ($this->gioi_tinh==1) {
            return "Nam";
        } else {
            return "Nữ";
        }
    }
    public function getTuoiAttribute()
    {
        $age = date_diff(date_create($this->ngay_sinh), date_create('now'))->y;
        return $age;
    }
}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Lop;
use App\Models\SinhVien;
use App\Imports\SinhVienImport;
use Maatwebsite\Excel\Facades\Excel;


class SinhVienController
{
	public function view_all()
	{
		$array_sinh_vien = SinhVien::with('lop')->get();
		return view('sinh_vien.view_all',compact('array_sinh_vien'));
	}
	public function view_insert()
	{
		$array_lop = Lop::get();
		return view('sinh_vien.view_insert',compact('array_lop'));
	}
	public function process_insert(Request $rq)
	{
		SinhVien::create($rq->all());

		return redirect()->route('sinh_vien.view_all');
	}
	public function view_update($ma)
	{
		$sinh_vien = SinhVien::find($ma);
		$array_lop = Lop::get();

		return view('sinh_vien.view_update',compact('sinh_vien','array_lop'));
	}
	public function process_update($ma, Request $rq)
	{
		SinhVien::find($ma)->update($rq->all());

		return redirect()->route('sinh_vien.view_all');
	}
	public function delete($ma)
	{
		// Lop::find($ma)->delete();

		Lop::destroy($ma);

		return redirect()->route('view_all');
	}
	public function view_sinh_vien_import()
	{
		return view('sinh_vien.view_sinh_vien_import');
	}
	public function process_sinh_vien_import(Request $rq)
	{
		Excel::import(new SinhVienImport, $rq->file_sinh_vien);
	}
}

resources/views/sinh_vien/view_all.blade.php
@extends('layout.master')

@section('content')
<h1>
	đây là danh sách sinh viên
</h1>
<a href="{{ route('sinh_vien.view_insert') }}">
	Thêm
</a>
<table class="table">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Email</th>
		<th>Tuổi</th>
		<th>Giới tính</th>
		<th>Tên lớp</th>
		<th>Sửa</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ma }}
			</td>
			<td>
				{{ $sinh_vien->ten }}
			</td>
			<td>
				{{ $sinh_vien->email }}
			</td>
			<td>
				{{ $sinh_vien->tuoi }}
			</td>
			<td>
				{{ $sinh_vien->ten_gioi_tinh }}
			</td>
			<td>
				{{ $sinh_vien->lop->ten }}
			</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.delete',['ma' => $sinh_vien->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

@endsection

resources/views/sinh_vien/view_insert.blade.php
<form action="{{ route('sinh_vien.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	Email
	<input type="email" name="email">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<button>Thêm</button>
</form>

resources/views/sinh_vien/view_sinh_vien_import.blade.php
<form action="{{ route('process_sinh_vien_import') }}" method="post" enctype="multipart/form-data">
	{{ csrf_field() }}
	Chọn file Excel
	<input type="file" name="file_sinh_vien">
	<button>Nhập vào</button>
</form>

resources/views/sinh_vien/view_update.blade.php
<form action="{{ route('sinh_vien.process_update',['ma' => $sinh_vien->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $sinh_vien->ten }}">
	<br>
	Email
	<input type="email" name="email" value="{{ $sinh_vien->email }}">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh" value="{{ $sinh_vien->ngay_sinh }}">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1"
	@if ($sinh_vien->gioi_tinh==1)
		checked 
	@endif
	>Nam
	<input type="radio" name="gioi_tinh" value="0"
	@if ($sinh_vien->gioi_tinh==0)
		checked 
	@endif
	>Nữ
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}"
			@if ($sinh_vien->ma_lop==$lop->ma)
				selected 
			@endif
			>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<button>Sửa</button>
</form>